# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'A-Lang' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
platform :ios, '10.0'
use_frameworks!

pod 'Firebase/Storage'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Auth'
pod 'expanding-collection', '~> 1.0.3'
pod 'EasyTipView', '~> 1.0.2'
pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'
pod 'ActiveLabel'
pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
pod 'FontAwesome.swift'
pod 'ObjectMapper'
pod 'FoldingCell', '~> 2.0.3'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "CKWaveCollectionViewTransition" || target.name == "EasyTipView" || target.name == "Spring" || target.name == "ActiveLabel" || target.name == "ChameleonFramework" || target.name == "FontAwesome.swift" || target.name == "FontAwesome_swift" || target.name == "FoldingCell" || target.name == "ObjectMapper"
            puts target
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end
